language: python
python: "2.7"
env:
  - PLONE_VERSION=4.2 TARGET=test
  - PLONE_VERSION=4.3 TARGET=test
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script: bin/$TARGET
